### ISSUE TITLE
There is a display error under Chinese language 

### ISSUE THREAD

**Issue by Daydreamer-riri** [Ashinch/ReadYou#488]
**1. Environment**

-   Device: [Pixel 8 pro]
-   OS: [Android 14]
-   APP: [0.9.8]
-   System font: ![Screenshot_20231112-104013.png](https://github.com/Ashinch/ReadYou/assets/70067449/92b66220-245f-46d9-936e-b6d5a053be4a)

**2. Describe the bug**

As shown in the picture, There are several situations where the layout is not fully displayed in the Chinese language.

![Screenshot_20231112-103739.png](https://github.com/Ashinch/ReadYou/assets/70067449/e84303e7-c2f8-470c-950a-7f4f12362d30)

![Screenshot_20231112-104119.png](https://github.com/Ashinch/ReadYou/assets/70067449/02dd59c3-a538-42fe-880d-33f9f3c277bf)

**Comment by naiyerasif** [comment]
Just so you know, the same thing happens with English as well with the following settings:

![Screenshot_20231115-045547~2](https://github.com/Ashinch/ReadYou/assets/19614213/ba51c9f5-a361-413b-b2b9-3ddc61eb782a)

To be fair, this line height issue also impacts other apps (such as default numpad form of keyboard) so I think this may not be entirely an issue with ReadYou.

---

Also, an aside: A separate line-height setting for headings would also make sense because for larger-size text (particularly h1 headings), the body line-height is just too small and the descenders (such as tails of `y`, `g`, etc) get cut off regardless of System Display Settings.

**Comment by Daydreamer-riri** [comment]
At present, I only encounter this problem in this app, I think maybe it is because of the use of a fixed height or line-height?
