### ISSUE TITLE
Add ability to change color of circles

### ISSUE THREAD

**Issue by ghost** [Ashinch/ReadYou#87]
**2. Describe the feature request**

We have these dark circles in front of the websites. I suggest allow changing these colors so we can more easily differentiate between articles based on source.

**Comment by Ashinch** [comment]
That's the place reserved for the favicon of websites. XD

**Comment by IHateTheProgrammingClass** [comment]
@Ashinch This could be an additional feature. Instead of favicons, user could set custom colors or the app can retrieve the main color of the favicon im order to represent the site. I would implement the latter first then users could override the automatically applied color. Of course only if they do not want to use the favicon itself, only the color of it.

**Comment by kou9221** [comment]
Why is favicons not showing for me? Or it is not properly working yet?

**Comment by Ashinch** [comment]
@kou9221 It's not done yet.
